apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
spec:
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
  volumes:
    items:
    - name: keycloak-cert
      mountPath: /etc/ssl/certs
      configMaps:
      - keycloak-tls-cert-ext
      items:
      - key: keycloak.crt
        path: keycloak.crt
  logLevel: debug
