apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
spec:
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
  volumes:
  - name: keycloak-cert
    configMap:
      name: keycloak-tls-cert-ext
      items:
      - key: keycloak.crt
        path: keycloak.crt
  volumeMounts:
  - name: keycloak-cert
    mountPath: /etc/ssl/certs/keycloak.crt
    subPath: keycloak.crt
    readOnly: true
  logLevel: debug
